import bmicalculator.General;
import bmicalculator.Pria;
import bmicalculator.Wanita;
import java.text.DecimalFormat;
import java.util.Collections;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import utility.CategoryBMIUtil;
import utility.DetailBMIUtil;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author silvi
 */


/**

Kelas Guest adalah kelas yang merepresentasikan jendela aplikasi untuk tamu.

Kelas ini digunakan untuk mengelola tampilan dan interaksi dengan pengguna.
*/
public class Guest extends javax.swing.JFrame {
    General userGeneral;
    boolean isINCI;
    boolean isPOUND;

    /**
     * Creates new form Guest
     */
    
/**

Konstruktor untuk membuat objek Guest baru.
Menginisialisasi komponen-komponen tampilan.
*/
    public Guest() {
        initComponents();
    }
    
  
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabelBMIjDialog = new javax.swing.JLabel();
        jLabelCategoryGuest = new javax.swing.JLabel();
        jLabelDetailGuest = new javax.swing.JLabel();
        jLabelIdealGuest = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tinggiGuest = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        wanita = new javax.swing.JRadioButton();
        pria = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        beratGuest = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        indeksBmiGuest = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        detailBmiGuest = new javax.swing.JButton();

        jDialog1.setPreferredSize(new java.awt.Dimension(600, 510));
        jDialog1.setSize(new java.awt.Dimension(600, 510));
        jDialog1.setType(java.awt.Window.Type.POPUP);

        jPanel6.setBackground(new java.awt.Color(146, 173, 255));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Point BMI");

        jLabelBMIjDialog.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabelBMIjDialog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBMIjDialog.setText("0");
        jLabelBMIjDialog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCategoryGuest.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabelCategoryGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCategoryGuest.setText("jLabel8");
        jLabelCategoryGuest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelDetailGuest.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabelDetailGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDetailGuest.setText("jLabel8");
        jLabelDetailGuest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelIdealGuest.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabelIdealGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIdealGuest.setText("0");
        jLabelIdealGuest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Berat Badan Ideal (dalam Kg)");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDetailGuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCategoryGuest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelBMIjDialog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jLabelIdealGuest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBMIjDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCategoryGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDetailGuest, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIdealGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        setLocationRelativeTo(null);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/g3.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("OCR A Extended", 3, 48)); // NOI18N
        jLabel5.setText("Mari Kita Hidup Sehat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(83, 83, 83))
        );

        jPanel2.setBackground(new java.awt.Color(146, 173, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("GUEST");

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setText("TINGGI");

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setText("BERAT");

        tinggiGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiGuestActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel8.setText("JENIS KELAMIN");

        buttonGroup1.add(wanita);
        wanita.setText("Wanita");
        wanita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wanitaMouseClicked(evt);
            }
        });
        wanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wanitaActionPerformed(evt);
            }
        });

        buttonGroup1.add(pria);
        pria.setText("pria");
        pria.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                priaStateChanged(evt);
            }
        });
        pria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priaMouseClicked(evt);
            }
        });
        pria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priaActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/girl.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/boy.png"))); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Satuan Tinggi", "CM", "INCI" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Satuan Berat", "KG", "POUNDS" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel4.setText("BMI");

        indeksBmiGuest.setEditable(false);
        indeksBmiGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indeksBmiGuestActionPerformed(evt);
            }
        });

        calculate.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        calculate.setText("CALCULATE");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        detailBmiGuest.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        detailBmiGuest.setText("CHECK DETAIL BMI");
        detailBmiGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailBmiGuestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(calculate)
                .addGap(47, 47, 47)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(indeksBmiGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tinggiGuest, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                                    .addComponent(beratGuest)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(wanita, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(199, 199, 199)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel1))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pria, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, 126, Short.MAX_VALUE))))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(detailBmiGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(pria)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wanita, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tinggiGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(beratGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(indeksBmiGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calculate)
                            .addComponent(clear)
                            .addComponent(exit))
                        .addGap(42, 42, 42)))
                .addComponent(detailBmiGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void wanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wanitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wanitaActionPerformed

    private void priaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priaActionPerformed

    private void tinggiGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiGuestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiGuestActionPerformed

    private void indeksBmiGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indeksBmiGuestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indeksBmiGuestActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        boolean isItemSelected = false;
        List<AbstractButton> listToggleButton = Collections.list(buttonGroup1.getElements());
        for (AbstractButton button : listToggleButton) {
            if (button.isSelected()) {
                isItemSelected = true;
                break;
            }
        }
        
        boolean isGenderSelected = false;
        if (wanita.isSelected()) {
            userGeneral = new Wanita();
            isGenderSelected = true;
        }
        
        if (pria.isSelected()) {
            userGeneral = new Pria();
            isGenderSelected = true;
        }
        
        if (!isItemSelected) {
        JOptionPane.showMessageDialog(this, "Anda belum memilih jenis kelamin","Pilihan Tidak Valid", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        // CHECK APAKAH MASUKKAN TINGGI KOSONG
        if (tinggiGuest.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tidak boleh kosong", "Masukkan tidak valid", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // CHECK APAKAH MASUKKAN BERAT KOSONG
        if (beratGuest.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tidak boleh kosong", "Masukkan tidak valid", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // // CHECK APAKAH MASUKKAN BERUPA ANGKA
        try {
            userGeneral.setTinggi(Double.parseDouble(tinggiGuest.getText()));
            userGeneral.setBerat(Double.parseDouble(beratGuest.getText()));
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Harus menggunakan angka", "Masukkan tidak valid", JOptionPane.ERROR_MESSAGE);
           return;
        }
        
        // CHECK APAKAH SUDAH MEMILIH SATUAN PANJANG
        if (jComboBox1.getSelectedItem().equals("Satuan Tinggi")) {
            JOptionPane.showMessageDialog(null, "Harap memilih satuan panjang", "Masukkan tidak valid", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // CHECK APAKAH SUDAH MEMILIH SATUAN BERAT
        if (jComboBox2.getSelectedItem().equals("Satuan Berat")) {
            JOptionPane.showMessageDialog(null, "Harap memilih satuan berat", "Masukkan tidak valid", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // CHECK APAKAH SUDAH MEMILIH PRIA ATAU WANITA
        if (userGeneral instanceof Pria) {
            Pria userPria = (Pria) userGeneral;
            userPria.setBmi(userPria.calculateBMI(userPria.getTinggi(), userPria.getBerat(), isINCI, isPOUND));
            userGeneral = userPria;
            System.out.println((double) userPria.getBmi());
            DecimalFormat ubah = new DecimalFormat("#.0");
            String a = ubah.format(userPria.getBmi());
            indeksBmiGuest.setText(a);
            return;
        } else if (userGeneral instanceof Wanita) {
            Wanita userWanita = (Wanita) userGeneral;
            userWanita.setBmi(userWanita.calculateBMI(userWanita.getTinggi(), userWanita.getBerat(), isINCI, isPOUND));
            userGeneral = userWanita;
            System.out.println(userWanita.getBmi());
            DecimalFormat ubah = new DecimalFormat("#.0");
            String a = ubah.format(userWanita.getBmi());
            indeksBmiGuest.setText(a);
            return;
        }
        
           
        
        
       
    }//GEN-LAST:event_calculateActionPerformed

    public String gender(){
        if(pria.isSelected()){
            return "Pria";
        }else{
            return "Wanita";
        }
    }  
    
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        tinggiGuest.setText("");
        beratGuest.setText("");
        indeksBmiGuest.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_clearActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        Kalmi kal = new Kalmi();
        kal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem().equals("CM")) {
            isINCI = false;
        } else if (jComboBox1.getSelectedItem().equals("INCI")) {
            isINCI = true;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void detailBmiGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailBmiGuestActionPerformed
        // TODO add your handling code here:
        try {
            if (indeksBmiGuest.getText().isEmpty()) {
            jLabelBMIjDialog.setText("0");
        } else {
            jLabelBMIjDialog.setText(indeksBmiGuest.getText());
        }
        
        // IMPLEMENTASI INTERFACE DENGAN STATIC METHOD
        if (indeksBmiGuest.getText().isEmpty()) {
            jLabelCategoryGuest.setText("-");
        } else {
            jLabelCategoryGuest.setText(CategoryBMIUtil.categoryBMI(Double.parseDouble(indeksBmiGuest.getText())));
        }
        
        // CONTOH INTERFACE DEFAULT METHOD
        if (indeksBmiGuest.getText().isEmpty()) {
            jLabelDetailGuest.setText("-");
        } else {
            jLabelDetailGuest.setText(userGeneral.detailBMI(Double.parseDouble(indeksBmiGuest.getText())));
        }
        
        // CONTOH INTERFACE PUBLIC METHOD
        if (indeksBmiGuest.getText().isEmpty()) {
            jLabelIdealGuest.setText("0");
        } else {
            String kg = " KG";
    
            jLabelIdealGuest.setText(Double.toString(userGeneral.idealMass(userGeneral.getTinggi(), isINCI)));
        }
        
        
        boolean isItemSelected = false;
        List<AbstractButton> listToggleButton = Collections.list(buttonGroup1.getElements());
        for (AbstractButton button : listToggleButton) {
            if (button.isSelected()) {
                isItemSelected = true;
                boolean isGenderSelected = false;
                try {
                    if (wanita.isSelected()) {
                        Wanita userWanita = (Wanita) userGeneral;
                        DecimalFormat ubah = new DecimalFormat("#.0");
                        String a = ubah.format(userWanita.idealMass(userWanita.getTinggi(), isINCI));
                        jLabelIdealGuest.setText(a + " KG");
                        this.jDialog1.setVisible(true);
                        this.jDialog1.setLocationRelativeTo(null);
                        isGenderSelected = true;
                    }
                    if (pria.isSelected()) {
                        Pria userPria = (Pria) userGeneral;
                        DecimalFormat ubah = new DecimalFormat("#.0");
                        String a = ubah.format(userPria.idealMass(userPria.getTinggi(), isINCI));
                        jLabelIdealGuest.setText(a + " KG");
                        this.jDialog1.setVisible(true);
                        this.jDialog1.setLocationRelativeTo(null);
                        isGenderSelected = true;
                    }
                    break;
                } catch (Exception e){
                
                }
            }
        }
        
        this.jDialog1.setVisible(true);
        this.jDialog1.setLocationRelativeTo(null);
        } catch (ClassCastException e){
            JOptionPane.showMessageDialog(null, "Klik clear untuk melihat detail informasi masukkan trebaru");
        }
    }//GEN-LAST:event_detailBmiGuestActionPerformed

    private void priaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_priaStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_priaStateChanged

    private void priaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_priaMouseClicked

    private void wanitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wanitaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_wanitaMouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if (jComboBox2.getSelectedItem().equals("KG")) {
            isPOUND = false;
        } else if (jComboBox2.getSelectedItem().equals("POUNDS")) {
            isPOUND = true;
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beratGuest;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calculate;
    private javax.swing.JButton clear;
    private javax.swing.JButton detailBmiGuest;
    private javax.swing.JButton exit;
    private javax.swing.JTextField indeksBmiGuest;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBMIjDialog;
    private javax.swing.JLabel jLabelCategoryGuest;
    private javax.swing.JLabel jLabelDetailGuest;
    private javax.swing.JLabel jLabelIdealGuest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton pria;
    private javax.swing.JTextField tinggiGuest;
    private javax.swing.JRadioButton wanita;
    // End of variables declaration//GEN-END:variables
}
