/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author silvi
 */
import bmicalculator.General;
import bmicalculator.Pria;
import bmicalculator.Wanita;
import java.util.*;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 * Kelas Login digunakan untuk mengatur tampilan dan logika yang terkait dengan proses login ke aplikasi.
 */

/**

Kelas Login adalah kelas yang merepresentasikan jendela aplikasi untuk proses login.

Kelas ini digunakan untuk mengelola tampilan dan interaksi dengan pengguna.
*/
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    /**

Variabel statement untuk eksekusi query database.
*/
    public Statement stm;
    /**

Variabel untuk koneksi ke database.
*/
    public Connection con;
    /**

Variabel untuk menyimpan pernyataan prepared statement.
*/
    public PreparedStatement pst;
    /**

Variabel untuk menyimpan hasil dari query database.
*/
    public ResultSet rs = null;
    /**

Variabel untuk menyimpan hasil dari query database.
*/
    public static String jenisKelamin;
    /**

Variabel untuk menyimpan username pengguna setelah login.
*/
    public static String userName;
   
    General user;
    /**

Metode untuk mendapatkan nilai coba.
@return Nilai dari variabel coba.
*/
    public String getCoba(){
    return coba;
    }
    /**

Metode untuk mengatur nilai coba.
@param coba Nilai yang akan diatur pada variabel coba.
*/
    public void setCoba(String coba){
     this.coba = usernameLogin.getText();
    }
    
     public class DisplayLogin{
        public DisplayLogin(){
            try{
                final String DATABASE_URL = "jdbc:mysql://localhost:3306/projectkalmi"; 
                String user = "root";
                String pass = "";
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(DATABASE_URL, "root", "");
                stm = con.createStatement();
              
                
            }catch(ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(null, "Connection Gagal");
            }
        }
    }
     
    /**
     * Membuat objek baru dari kelas Login.
     * Metode ini akan menginisialisasi komponen-komponen pada tampilan dan menampilkan tampilan login.
     */
    public Login() {
        initComponents();
        new DisplayLogin();
    }

    String coba;
  
    
  
/**

Metode ini digunakan untuk memeriksa login pengguna dengan membandingkan
username dan password yang diberikan dengan data registrasi yang ada di database.
@param usernameLogin Username yang dimasukkan oleh pengguna saat login.
@param passwordLogin Password yang dimasukkan oleh pengguna saat login.
@return True jika username dan password cocok dengan data registrasi yang ada,
*/
    
  public boolean checkLogin(String usernameLogin, String passwordLogin)
            {
                try {
                     String sqlcom = "select * from data_registrasi";
                     rs = con.createStatement().executeQuery(sqlcom);
                    while(rs.next()){
                        if(usernameLogin.equals(rs.getString("username")) && passwordLogin.equals(rs.getString("password"))){
                            return true;
                        }
                    }
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
                return false;
                
                
            } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameLogin = new javax.swing.JTextField();
        passwordLogin = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        cekPass = new javax.swing.JCheckBox();
        login = new javax.swing.JButton();
        sign = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/slogan.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("OCR A Extended", 3, 48)); // NOI18N
        jLabel11.setText("WELCOME TO KALMI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );

        jPanel2.setBackground(new java.awt.Color(146, 173, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("LOG IN NOW");

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setText("USERNAME");

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setText("PASSWORD");

        passwordLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordLoginActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/PW.png"))); // NOI18N

        cekPass.setText("Show Password");
        cekPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekPassActionPerformed(evt);
            }
        });

        login.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        sign.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        sign.setText("don't have an account? Sign Up now!");
        sign.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ORNG.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cekPass)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(sign)
                                .addGap(100, 100, 100))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(156, 156, 156)))))
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cekPass)
                .addGap(40, 40, 40)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sign)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metode yang dipanggil ketika opsi cek password diubah.
     * Metode ini akan menampilkan karakter password atau karakter '*' tergantung pada status opsi cek password.
     * @param evt Objek ActionEvent yang memicu pemanggilan metode
     */
    private void cekPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekPassActionPerformed
        // TODO add your handling code here:
        if(cekPass.isSelected()) {
            passwordLogin.setEchoChar((char)0);
        }else{
            passwordLogin.setEchoChar('*');
        }
    }//GEN-LAST:event_cekPassActionPerformed
    /**
     * Metode yang dipanggil ketika ada aksi pada field password.
     * Metode ini dapat diimplementasikan untuk menangani aksi yang terjadi saat pengguna melakukan interaksi dengan field password.
     * @param evt Objek ActionEvent yang memicu pemanggilan metode
     */
    private void passwordLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordLoginActionPerformed
 /**
     * Metode yang dipanggil ketika tombol sign up di-klik.
     * Metode ini akan membuka tampilan SignUp dan menutup tampilan Login.
     * @param evt Objek MouseEvent yang memicu pemanggilan metode
     */
    private void signMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signMouseClicked
        // TODO add your handling code here:
        SignUp sign = new SignUp();
        sign.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signMouseClicked

    /**
     * Metode yang dipanggil ketika tombol login di-klik.
     * Metode ini akan memeriksa username dan password yang dimasukkan, serta melakukan tindakan berdasarkan hasilnya.
     * Jika username dan password benar, maka akan ditampilkan pesan selamat datang dan membuka tampilan HitungBmi.
     * Jika username dan password salah, maka akan ditampilkan pesan kesalahan.
     * @param evt Objek ActionEvent yang memicu pemanggilan metode
     */
    
    
/**

Metode yang akan dipanggil saat tombol "Login" di klik.

Metode ini digunakan untuk melakukan login pengguna dan menampilkan jendela HitungBmi setelah login berhasil.
*/
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
      
       SignUp obj = new SignUp();
       String check = obj.getTest();
      
  
        String tampungun = usernameLogin.getText();
        String tampungpw = passwordLogin.getText();
        String tampungjk = obj.gender();
      
        if(checkLogin(tampungun, tampungpw)){
            if(usernameLogin.getText() == check){
               JOptionPane.showMessageDialog(null, "Halo, " + tampungun + " Ketahui Hasil BMI-mu YUK!", "Message", JOptionPane.INFORMATION_MESSAGE);
              

         
     
            }
             JOptionPane.showMessageDialog(null, "Halo, " + tampungun + " Ketahui Hasil BMI-mu YUK!", "Message", JOptionPane.INFORMATION_MESSAGE);
              
             HitungBmi bmi = new HitungBmi();
             
            try {

                String sqlcom = "select jeniskelamin, username from data_registrasi WHERE username = '" + tampungun + "'";
                rs = con.createStatement().executeQuery(sqlcom);
                while(rs.next()){
                    jenisKelamin = rs.getString("jeniskelamin");
                    userName = rs.getString("username");
                    
                    
                    //Login obj2 = new Login();
              
                    
                   bmi.cekKelamin.setText(jenisKelamin);
                   HitungBmi.SIMPAN_NAMA = (userName);
                   
        
                }
            } catch (Exception e) {
                System.out.println(e.toString());
            }
            this.dispose();    
            bmi.setVisible(true);
     
        }else{
              JOptionPane.showMessageDialog(null, "Pastikan username dan password yang Anda masukkan benar", "Login", JOptionPane.ERROR_MESSAGE); 
            
            }
        
        
       
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cekPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField passwordLogin;
    private javax.swing.JLabel sign;
    private javax.swing.JTextField usernameLogin;
    // End of variables declaration//GEN-END:variables
}
